### ISSUE TITLE
Muted players incorrectly steal the audio session

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgletterbox-ios#180]
When using an audio app, opening an application using Letterbox for playback (with the player muted) stops playback of the first audio application. This should not be the case.

### Issue type

Incorrect behavior

### Environment information

* Library version: Any
* iOS version: Any
* Device: Physical

### Reproducibility

Always reproducible

### Steps to reproduce

1. Play some audio with a dedicated app (e.g. Spotify).
1. Open Letterbox demo. Audio continues in the background
1. Open one of the Autoplay demos, for which players all are muted. Audio stops, but shouldn't.

**Comment by pyby** [comment]
`AVPlayer` playing with `muted = YES` has an active audio session.

To allow audio from other applications, the `AVAudioSessionCategoryOptionMixWithOthers` options has to be set to the category. this option is only available on some categories, included `AVAudioSessionCategoryPlayback`, the one we use.

Proposition 1 is to add a property on service to set or remove it.
I'm not convince to track all `SRGLetterboxController` instance to listen `muted` and `playbackState` change.

**Comment by pyby** [comment]
After a discussion with @fredhdroz, the application should manage the `AVAudioSession` itself.

Proposition 2:
- Set `AVAudioSessionCategoryPlayback` with no option at the service initialisation, first time. It will cover most applications usage.
- If the application wants to manage options, it's its responsabilty.
- Don't change the category when disable a controller from the service, as it may not required by an application playing content.

`disable` on `SRGService` should be retested and documentation updated.

See `feature/audio-session-muted`.

**Comment by defagos** [comment]
Fixed. Audio session management has been entirely removed from Letterbox.
